### ISSUE TITLE
As a user I want to see active item highlighted in a sidebar according to current page

### ISSUE THREAD

**Issue by okendoken** [flatlogic/angular-dashboard-seed#1]
Please use [`ui-sref-active`](http://angular-ui.github.io/ui-router/site/#/api/ui.router.state.directive:ui-sref-active) for that.

**Comment by okendoken** [comment]
Reopening as it is still not working when on a 2nd level page (top level is not highlighted).
Please also correct urls to match levels (e.g. create new post is /app/posts/new)

**Comment by smartapant** [comment]
Made it work, thanks.
