### ISSUE TITLE
cant find /app/index.css after a fresh installation

### ISSUE THREAD

**Issue by ofershap** [flatlogic/angular-dashboard-seed#11]
i've installed using npm install, and gulp serve, and receive error 404 on index.css file

**Comment by JanLoebel** [comment]
I had the same problem and in the logs there was a hint that "sass" was missing.

`[16:00:24] gulp-ruby-sass: stderr: The command "sass" could not be found.`

So you would have to install it via like described here: http://sass-lang.com/install

**Comment by eperinan** [comment]
I had the same problem too. I think that in the README in "Required tools" we should to put Saas with Gulp, Bower and Node and npm.

Should I create a Pull Request with it?

**Comment by DimaSavchenko** [comment]
Thanks guys!
