### ISSUE TITLE
Live demo site is down of sth?

### ISSUE THREAD

**Issue by x-bingxin** [flatlogic/angular-dashboard-seed#12]
Thanks for sharing, but the live demo seems some issue occurred.

**Comment by okendoken** [comment]
Hi @Bing-Xia,

yes, correct. It's down. We are investigating the issue.

Thanks for the report

**Comment by okendoken** [comment]
Should be fixed as of now, seems like we run out of resources
https://angular-dashboard-demo.herokuapp.com/#/login
