### ISSUE TITLE
Pressing browser back after logging out just keeps logging out.

### ISSUE THREAD

**Issue by beezenees** [flatlogic/angular-dashboard-seed#3]
Reproduce,
- login
- logout
- try to go back (via browser back button)
- endless refresh with notification of `you have logged out successfully`

**Comment by lugovsky** [comment]
Hi Jess!

Thanks a lot for such quick issue report :). Could you please tell, what browser are you using. Can't reproduce this endless refresh in Chrome, FF or Safari

Cheers,
Vlad

**Comment by beezenees** [comment]
Hi :D I am in Chrome Version 41.0.2272.89 (64-bit) for Mac Yosemite.

**Comment by lugovsky** [comment]
Logout was modified to show notification only once. Endless refresh wasn't reproduced unfortunately
